### PR TITLE
Add PowerUnifSampler

### PR DESCRIPTION
**Pull request by elsander**
This PR adds a utility distribution for use with hyperband.

### CODE REVIEW

**Comment by elsander** [comment]
Do you think tests are necessary here, @stephen-hoover? I'm not sure what would be a useful test for a simple sampler like this.

**Comment by elsander** [comment]
Yeah, it was such a small class that I hesitated to make a new module for it, but I agree that it's not really part of hyperband.

As for subclassing from rv_continuous, that would involve doing some math to figure out the pdf, cdf, etc. It's something I can do, but I'm not sure it's worth the additional time and effort, since we're not getting any additional value out of it (at least right now). I'm going to spend a little time looking for an alternate distribution that does something similar, maybe the truncated exponential: https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.truncexpon.html

**Comment by stephen-hoover** [comment]
Okay, I can agree that it's not worth the effort to make this a full scipy distribution at this time. You should put a note in the class docstring about it being similar to an `rv_continuous` in some ways, but not a full subclass.

**Comment by elsander** [comment]
I lean toward switching to the truncated exponential, and not including this in civisml-extensions at all. It will take a little more time to figure out what distributions to use in CivisML, but the scipy distribution is more fully supported and fleshed out, and it'll be easier for users to understand.

**Comment by stephen-hoover** [comment]
I think that sounds fine, if you think it's best. But I also think it's reasonable to add a cut-down distribution with appropriate documentation here. The truncated exponential is a different distribution from what this does.

**Comment by elsander** [comment]
I wouldn't mind including a cut-down distribution here if we had a strong justification for using it. But the distribution was a kind of arbitrary choice anyway, so I lean toward using an existing distribution that does something similar. I think as a CivisML user who encountered this distribution in my estimator, I might be a little confused.

**Comment by elsander** [comment]
Closing this and switching to a truncated exponential in CivisML.

**Pull request closed without merging**
